// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class TempCol : MonoBehaviour
{
    public TextAsset file;
    int textemp;
    public void Start()
    {
        Load(file);
        for (int i = 1; i >= 0; i++)
        {
            textemp = int.Parse(Find_id(i.ToString()).temp);
        }
    }
    private void Update()
    {
        if (textemp >= 25 && textemp <= 28)
        {
            GetComponent<Renderer>().material.color = Color.green;
        }
        else if (textemp >= 0 && textemp < 25 || textemp >= 28 && textemp <= 32)
        {
            GetComponent<Renderer>().material.color = Color.yellow;
        }
        else if (textemp < 0 || textemp > 32)
        {
            GetComponent<Renderer>().material.color = Color.red;
        }

    }
    public class Row
    {
        public string id;
        public string temp;
        public string humid;
        public string uv;
        public string co;
        public string co2;
        public string h2;

    }

    List<Row> rowList = new List<Row>();
    bool isLoaded = false;

    public bool IsLoaded()
    {
        return isLoaded;
    }

    public List<Row> GetRowList()
    {
        return rowList;
    }

    public void Load(TextAsset csv)
    {
        rowList.Clear();
        string[][] grid = CsvParser2.Parse(csv.text);
        for (int i = 1; i < grid.Length; i++)
        {
            Row row = new Row();
            row.id = grid[i][0];
            row.temp = grid[i][1];
            row.humid = grid[i][2];
            row.uv = grid[i][3];
            row.co = grid[i][4];
            row.co2 = grid[i][5];
            row.h2 = grid[i][6];

            rowList.Add(row);
        }
        isLoaded = true;
    }

    public int NumRows()
    {
        return rowList.Count;
    }

    public Row GetAt(int i)
    {
        if (rowList.Count <= i)
            return null;
        return rowList[i];
    }

    public Row Find_id(string find)
    {
        return rowList.Find(x => x.id == find);
    }
    public List<Row> FindAll_id(string find)
    {
        return rowList.FindAll(x => x.id == find);
    }
    public Row Find_temp(string find)
    {
        return rowList.Find(x => x.temp == find);
    }
    public List<Row> FindAll_temp(string find)
    {
        return rowList.FindAll(x => x.temp == find);
    }
    public Row Find_humid(string find)
    {
        return rowList.Find(x => x.humid == find);
    }
    public List<Row> FindAll_humid(string find)
    {
        return rowList.FindAll(x => x.humid == find);
    }
    public Row Find_uv(string find)
    {
        return rowList.Find(x => x.uv == find);
    }
    public List<Row> FindAll_uv(string find)
    {
        return rowList.FindAll(x => x.uv == find);
    }
    public Row Find_co(string find)
    {
        return rowList.Find(x => x.co == find);
    }
    public List<Row> FindAll_co(string find)
    {
        return rowList.FindAll(x => x.co == find);
    }
    public Row Find_co2(string find)
    {
        return rowList.Find(x => x.co2 == find);
    }
    public List<Row> FindAll_co2(string find)
    {
        return rowList.FindAll(x => x.co2 == find);
    }
    public Row Find_h2(string find)
    {
        return rowList.Find(x => x.h2 == find);
    }
    public List<Row> FindAll_h2(string find)
    {
        return rowList.FindAll(x => x.h2 == find);
    }

}